name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ['8.1']
        racket-variant: ['BC', 'CS']
        allow-failure: [false]
        include:
          - racket-version: 'stable'
            racket-variant: 'CS'
            allow-failure: false
          - racket-version: 'current'
            racket-variant: 'CS'
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    name: Racket ${{ matrix.racket-version }} (${{ matrix.racket-variant }})
    steps:
      - uses: actions/checkout@v6
      - uses: Bogdanp/setup-racket@v1.14
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
          variant: ${{ matrix.racket-variant }}
      - run: raco pkg install --auto --no-docs
      - run: raco test -j $(nproc) .
